title: "Engineering & AI the Right Way"
description: >-
  Exploring thoughtful approaches to building resilient engineering systems and using artificial intelligence professionally.
baseurl: ""
url: ""
lang: en
languages:
  en: English
  vi: Tiếng Việt

# Build settings
markdown: kramdown
theme: minima

author:
  name: "Engineering & AI the Right Way"
  email: "hieutrantrung.it@gmail.com"

social_links:
  github: hieutrtr
  linkedin: "https://www.linkedin.com/in/hieu-tran-data"
